### ISSUE TITLE
Unable to parse resource id when resource name includes the character "@"

### ISSUE THREAD

**Issue by pacfernandes-bosch** [pulumi/pulumi-rabbitmq#146]
### What happened?

I'm trying to use Pulumi's RabbitMQ provider to deploy several resources. One of the resources I need to create is a Queue, which is throwing an error when pulumi tries to parse the id generated

```
Diagnostics:
    pulumi:pulumi:Stack (rabbitmq-cfg-qa):
      error: update failed

    rabbitmq:index:Queue (tic-queue-xmpp-time-de-qa):
      error: 1 error occurred:
      	* creating urn:pulumi:qa::rabbitmq-cfg::rabbitmq:index/queue:Queue::tic-queue-xmpp-time-de-qa: 1 error occurred:
      	* Unable to parse resource id: gservice_time@xmpp.de#gsxmpp@connectivity_vh
```

On further inspection, it seems that the error occurs due to the fact that the name of the queue includes an "@".
The id for the resource is generated using the format "<queue_name>@<vhost>", but it seems that pulumi is not able to correctly process the id when the name includes an "@"

The name of the queue must be maintained, changing it is not currently an option. As such, would it be possible to change the providers' behavior to be able to process the fact that the name of the queue (or other resource) may contain the "@" one or multiple times?

On a final note, even though an error is thrown, which eventually stops the deployment process, the queue is correctly created and the resource is added to the state file.

### Expected Behavior

RabbitMQ provider is able to process id's from resources that include "@" the name

### Steps to reproduce

```
import pulumi_rabbitmq as rabbitmq

# Creation of the connectivity vhost
vhost_connectivity = rabbitmq.VHost(
    resource_name=f"tic-connectivity-vhost",
    name="connectivity_vh"
)

user_xmpp_adapter_time_de = rabbitmq.User(
    resource_name=f"tic-user-xmpp-adapter-time-de",
    name="xmpp-adapter-time-de",
    password="TODO",
    tags=["monitoring"]
)

# Creation of user permissions
user_permissions_xmpp_adapter_time_de = rabbitmq.Permissions(
    resource_name=f"tic-user-permissions-xmpp-adapter-time-de",
    permissions=rabbitmq.PermissionsPermissionsArgs(
        configure=".*",
        read=".*",
        write=".*",
    ),
    user=user_xmpp_adapter_time_de.name,
    vhost=vhost_connectivity.name
)

# Creation of xmpp queues for service time
queue_xmpp_time_de = rabbitmq.Queue(
    resource_name=f"tic-queue-xmpp-time-de",
    name="gservice_time@xmpp.de#gsxmpp",
    settings=rabbitmq.QueueSettingsArgs(
        durable=True,
        auto_delete=False,
        arguments={
            "x-queue-type": "quorum",
        }
    ),
    vhost=user_permissions_xmpp_adapter_time_de.vhost,
)
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @pacfernandes-bosch, thanks for reporting this. It looks like the upstream provider constructs the ID by combining `name` and `vhost`: https://github.com/cyrilgdn/terraform-provider-rabbitmq/blob/v1.8.0/rabbitmq/resource_queue.go#L83-L110

And the ID must contain only a single "@": https://github.com/cyrilgdn/terraform-provider-rabbitmq/blob/v1.8.0/rabbitmq/util.go#L44-L53

Is it possible to change your queue names to drop the "@"? I'm not sure if it's valid to have multiple at symbols in the name when parsing out the vhost requires splitting on the symbol.

**Comment by pacfernandes-bosch** [comment]
Seem like the problem comes from above, then. Moreover, a similar issue is open on the upstream provider as well
https://github.com/cyrilgdn/terraform-provider-rabbitmq/issues/33
As such i will close this for now, thanks
