### ISSUE TITLE
json: cannot unmarshal array into Go struct field UserInfo.tags of type string

### ISSUE THREAD

**Issue by Narrayahodeir** [pulumi/pulumi-rabbitmq#62]
When I add a user to my newly created RabbitMQ instance I get the following error message:

`Preview failed: refreshing urn:pulumi:xxx-xxx-xxx-mqservice::mqservice::rabbitmq:index/user:User::user: json: cannot unmarshal array into Go struct field UserInfo.tags of type string`

## Steps to reproduce
1. In my case I have a fresh new RabbitMQ instance version 3.9.0 provided by CloudAMQP. I also used a RabbitMQ Docker container.
2. Setup a new Pulumi project and stack using Node as runtime. Insert the following code to index.ts:
```
import * as pulumi from "@pulumi/pulumi";
import * as rabbitmq from "@pulumi/rabbitmq";

const test = new rabbitmq.User("user", {
    password: "foobar",
    tags: [
        "administrator",
        "management",
    ],
});
```
3. Execute `pulumi up`
4. Repeat with omitting the tags and change the runtime to python does not help either.

Expected: I expect no error while creating just a user. 
Actual: I got the error message described above. Interestingly the user in being properly added, anyway. I checked that in the RabbitMQ management console.

As I just figured out the problem just occurs with RabbitMQ version 3.9.0. Version 3.8.19 works

**Comment by leezen** [comment]
I suspect this may have to do w/ the supported API versions of the underlying provider:
> The provider supports verions 3.8.x and 3.7.x of RabbitMQ. It may still work with version3.6.x, however this version is no longer supported.
(per https://github.com/cyrilgdn/terraform-provider-rabbitmq)

We should likely add similar text to our repo and docs.

**Comment by mikhailshilkov** [comment]
I tried the repro above today with 3.3.0 and received no errors. I'll assume the issue has been fixed.
